<?php

/**
 * @file
 * Personified module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function personified_theme() {
  return [
    'personified_data' => [
      'variables' => [
        'endpoint' => '',
        'template' => '',
        'params' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for a Personified Data template.
 *
 * Default template: personified-data.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of block types.
 */
function template_preprocess_personified_data(&$variables) {
  $counter = &drupal_static(__FUNCTION__, 0);
  $id = Html::getId('personified-data-' . $counter++);

  $variables['attributes']['id'] = $id;
  $variables['#attached']['library'] = 'personified/init';
  $variables['#attached']['drupalSettings']['personified'][$id] = [
    'endpoint' => $variables['endpoint'],
    'template' => $variables['template'],
    'params' => $variables['params'],
  ];
}
